### ISSUE TITLE
System.ArgumentException 'User-Agent' header must be modified using the appropriate property or method.

### ISSUE THREAD

**Issue by GonzoKK** [JKorf/CoinEx.Net#6]
Occurs with latest update on GetMarketStatesAsync

Parameter name: name
  Source=System
  StackTrace:
   at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
   at CoinEx.Net.CoinExClient.ConstructRequest(Uri uri, String method, Dictionary`2 parameters, Boolean signed)
   at CryptoExchange.Net.RestClient.<ExecuteRequest>d__24`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CoinEx.Net.CoinExClient.<Execute>d__70`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CoinEx.Net.CoinExClient.<GetMarketStatesAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <GetCoinEx_MarketStatesAsync>d__1.MoveNext() in C:

**Comment by JKorf** [comment]
Hm I don't have this. Are you using .Net core or the .Net framework(i.e. v4.6.1)?

**Comment by GonzoKK** [comment]
4.6.1

**Comment by JKorf** [comment]
I tested on 4.6.1 and apparently it handles the user-agent header differently than .Net Core. Anyway, I pushed a new version which should be available in a few seconds with a fix for this.

**Comment by GonzoKK** [comment]
Fixed in 2.0.2 Thanks.
